id: d78e3a175c4245e892dbd292eb377cab
initial_creation_type: ocr
source_metadata:
  volumes:
    a6cb0edb25b5455589c07df34b4c24ce:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: རྡོ་རྗེ་ཁྲོ་བོ་གཏུམ་པོ་ལྷ་ལྔ་པ་ཞེས་བྱ་བའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1853
      volume_number: 25
